#!/usr/bin/env bash
# setup.sh — StaticFDP Index interactive setup
# =============================================
# Part of the StaticFDP ecosystem (https://github.com/StaticFDP)
set -euo pipefail

G='\033[0;32m'; B='\033[0;34m'; Y='\033[1;33m'; R='\033[0m'

echo -e "${G}"
cat << 'EOF'
  ╔══════════════════════════════════════════════════════╗
  ║          StaticFDP Index — setup                     ║
  ║  FDP discovery catalog on static hosting             ║
  ╚══════════════════════════════════════════════════════╝
EOF
echo -e "${R}"
echo "This script writes fdp-index-config.yaml with your deployment settings."
echo ""

# ── Q1: Platform ──────────────────────────────────────────────────────────────
echo -e "${B}Where should the FDP Index be hosted?${R}"
echo "  1) GitHub Pages only           (Microsoft, US jurisdiction)"
echo "  2) Codeberg Pages only         (Hetzner Frankfurt, EU jurisdiction)"
echo "  3) Both (dual-write, active-active)"
read -rp "Choice [1/2/3]: " PLATFORM_CHOICE

case "$PLATFORM_CHOICE" in
  2) PRIMARY="codeberg"; GH_ENABLED="false"; CB_ENABLED="true";;
  3) PRIMARY="both";     GH_ENABLED="true";  CB_ENABLED="true";;
  *) PRIMARY="github";   GH_ENABLED="true";  CB_ENABLED="false";;
esac

# ── Q2: GitHub ────────────────────────────────────────────────────────────────
GH_REPO="OWNER/staticfdp-index"
GH_PAGES="https://OWNER.github.io/staticfdp-index"
if [[ "$GH_ENABLED" == "true" ]]; then
  echo ""
  echo -e "${B}GitHub settings${R}"
  read -rp "  GitHub repo (OWNER/REPO): " GH_REPO
  GH_OWNER="${GH_REPO%%/*}"
  GH_NAME="${GH_REPO##*/}"
  GH_PAGES="https://${GH_OWNER}.github.io/${GH_NAME}"
  read -rp "  GitHub Pages URL [${GH_PAGES}]: " _tmp
  GH_PAGES="${_tmp:-$GH_PAGES}"
fi

# ── Q3: Codeberg ──────────────────────────────────────────────────────────────
CB_REPO="OWNER/staticfdp-index"
CB_PAGES="https://OWNER.codeberg.page/staticfdp-index"
if [[ "$CB_ENABLED" == "true" ]]; then
  echo ""
  echo -e "${B}Codeberg settings${R}"
  read -rp "  Codeberg repo (OWNER/REPO): " CB_REPO
  CB_OWNER="${CB_REPO%%/*}"
  CB_NAME="${CB_REPO##*/}"
  CB_PAGES="https://${CB_OWNER}.codeberg.page/${CB_NAME}"
  read -rp "  Codeberg Pages URL [${CB_PAGES}]: " _tmp
  CB_PAGES="${_tmp:-$CB_PAGES}"
fi

# ── Q4: FDP Index identity ────────────────────────────────────────────────────
echo ""
echo -e "${B}FDP Index identity${R}"
BASE_URL="$GH_PAGES"
[[ "$PRIMARY" == "codeberg" ]] && BASE_URL="$CB_PAGES"
read -rp "  Canonical public URL [${BASE_URL}]: " _tmp
BASE_URL="${_tmp:-$BASE_URL}"
read -rp "  Index title [My FDP Index]: " TITLE
TITLE="${TITLE:-My FDP Index}"
read -rp "  Publisher name [My Organisation]: " PUB_NAME
PUB_NAME="${PUB_NAME:-My Organisation}"
read -rp "  Publisher URL [https://example.org/]: " PUB_URL
PUB_URL="${PUB_URL:-https://example.org/}"

# ── Write config ──────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/../fdp-index-config.yaml"

cat > "$CONFIG" << YAML
# FDP Index Configuration
# Generated by scripts/setup.sh on $(date +%Y-%m-%d)

fdp_index:
  title: "${TITLE}"
  base_url: ${BASE_URL}
  license: https://creativecommons.org/licenses/by/4.0/
  publisher_name: "${PUB_NAME}"
  publisher_url: ${PUB_URL}

infrastructure:
  primary: ${PRIMARY}

  github:
    enabled: ${GH_ENABLED}
    repo: ${GH_REPO}
    pages_url: ${GH_PAGES}

  codeberg:
    enabled: ${CB_ENABLED}
    repo: ${CB_REPO}
    base_url: https://codeberg.org
    pages_url: ${CB_PAGES}

harvest:
  schedule: "25 4 * * *"
  timeout_seconds: 30
  soft_fail: true
YAML

echo ""
echo -e "${G}✓ Written: fdp-index-config.yaml${R}"
echo ""
echo -e "${Y}Next steps:${R}"
echo "  1. Commit fdp-index-config.yaml"
if [[ "$GH_ENABLED" == "true" ]]; then
  echo "  2. Enable GitHub Pages (Settings → Pages → Branch: main, Path: /docs)"
  echo "     Set secret: GITHUB_TOKEN (fine-grained PAT, Contents: Read & Write)"
fi
if [[ "$CB_ENABLED" == "true" ]]; then
  echo "  3. Push to Codeberg and enable Codeberg Pages"
  echo "     Add secret FORGEJO_TOKEN in Woodpecker CI settings"
fi
echo ""
echo "  Done! The harvest pipeline runs daily and on every new registration issue."
